cleaned some unneeded env vars added a clean script to remove all the tools dependencies and build artifacts modularised and added more check to the regression generators simplified parsing of forge output tables, would be better if they output in, e.g. json added a script for test

diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -2,8 +2,31 @@
 set -e
 set -o pipefail
 
-# clean up the toos cache
-rm -rf /home/tfras/.cache/pypoetry/virtualenvs/bao-base-bin-modules*
-
 # clean the build artifacts
 forge clean
+echo "cleaned build artifacts"
+
+# clean up the tools cache
+
+clean_directory() {
+    local dir="$1"
+
+    # Check if the directory contains a poetry project
+    if [[ -f "$dir/pyproject.toml" ]]; then
+        # Get the virtual environment path
+        VENV_PATH=$(cd $dir && poetry env info --path 2>/dev/null)
+
+        if [[ $? -eq 0 && -d "$VENV_PATH" ]]; then
+            # Delete the virtual environment
+            rm -rf "$VENV_PATH"
+            echo "for $dir, cleaned: $VENV_PATH"
+        fi
+    fi
+}
+
+# Export the function for use in subshells
+export -f clean_directory
+
+# Recursively find all directories and process them
+find "$BAO_BASE_LIB_DIR" -type d -exec bash -c 'clean_directory "$0"' {} \;
+echo "cleaned tools dependencies"
