make regression testing more robust to errors in the test script fix parse error not allowing digits in a function name

diff --git a/bin/regression-of b/bin/regression-of
--- a/bin/regression-of
+++ b/bin/regression-of
@@ -15,7 +15,12 @@ info1 "generating regression for ${REGRESSION_TYPE}..."
 # tee >(sed 's/\x1b\[[0-9;]*m//g' > logfile.log)
 # shellcheck disable=SC2154 # we don't need to check if the variable is set
 . "${BAO_BASE_DIR}/run" "${REGRESSION_TYPE}" "$@" | tee "${GENERATED_LOG}"
+run_status=${PIPESTATUS[0]}
 debug "generating ${REGRESSION_TYPE} file complete."
+
+if [[ "$run_status" -ne 0 ]]; then
+  error "${REGRESSION_TYPE} failed (exit code ${run_status}). Fix the failing tests before running regression."
+fi
 
 # process it using the filter
 # shellcheck disable=SC2154 # we don't need to check if the variable is set
