added shellcheck for bash scripts various fixes as a result of adding shellcheck more code for deplot script - it's looking very hard to get working reliably

diff --git a/bin/modules/argparsing b/bin/modules/argparsing
--- a/bin/modules/argparsing
+++ b/bin/modules/argparsing
@@ -1,8 +1,11 @@
 #!/bin/bash
+set -e -o pipefail
 
 if [[ -n "${GUARD_SOURCING_ARGPARSING:-}" ]]; then return; fi; GUARD_SOURCING_ARGPARSING=1
+[[ -n "${LOADING:-}" ]] && echo "loading ${BASH_SOURCE[0]}..."
 
-source $(dirname "${BASH_SOURCE[0]}")/logging
+
+source "$(dirname ${BASH_SOURCE[0]})/logging"
 
 ######################################
 # JSON args / command line conversion
@@ -10,20 +13,20 @@ source $(dirname "${BASH_SOURCE[0]}")/logging
 
 # convert a command line to JSON args
 argparsing_argparse() {
-    logging debug "$FUNCNAME($*)..."
+    logging trace "${FUNCNAME[0]}($*)..."
     # run the python argparse wrapper from the same directory
-    # remove the null values. need to pass it through jq -c anyway
-    local output=$($(dirname "${BASH_SOURCE[0]}")/wargparse.py "$@")
-    logging debug "wargparse.py->'$output'"
-    output=$(echo "$output" | jq -rc '.known |= with_entries(select(.value.value != null))')
-    logging debug "$FUNCNAME->'$output'"
+    local output
+    output=$("$(dirname ${BASH_SOURCE[0]})/wargparse.py" "$@") || exit $?
+    [[ ! "$output" == "" ]] || logging fail "parsing error"
+    logging debug "wargparse.py->$output."
+    output=$(echo "$output" | jq -rc '.known |= with_entries(select(.value.value != null))') || exit $?
+    logging trace "${FUNCNAME[0]}->${output}."
     echo "$output"
 }
 
-
 # convert a JSON args to a command line
 argparsing_args() {
-    logging debug "$FUNCNAME($*)..."
+    logging trace "${FUNCNAME[0]}($*)..."
     local json_args="$1"
     shift
     local args=("$@")
@@ -39,18 +42,38 @@ argparsing_args() {
         known)
             if [ $known -eq 0 ]; then
                 known=1
-                # logging debug "processing knowns..."
                 this_output=$(jq -r '
                     if .known then
                         .known
                         | to_entries
                         | map(select(.value.value != null))
-                        | map((if .value.origin != null then (.value.origin + " ") else "" end) + "'\''" + .value.value + "'\''")
+                        | map(
+                            if (.value.value | type) == "boolean" and .value.value == false then
+                                ""  # Omit entirely if the boolean is false
+                            else
+                                (if .value.origin != null then
+                                    (.value.origin + " ")
+                                elif .value.default_origin != null then
+                                    (.value.default_origin + " ")
+                                else
+                                    ""  # positional; no origin
+                                end)
+                                +
+                                (if (.value.value | type) == "boolean" then
+                                    ""  # For boolean true, output nothing for the value
+                                elif (.value.value | type) == "array" then
+                                    "'\''" + (.value.value | join("'\'' '\''")) + "'\''"
+                                else
+                                    "'\''" + (.value.value | tostring) + "'\''"
+                                end)
+                            end
+                        )
+                        | map(select(length > 0))
                         | join(" ")
                     else
                         ""
                     end
-                ' <<< "$json_args" )
+                    ' <<< "$json_args") || exit $?
             fi
             ;;
         unknown)
@@ -68,7 +91,7 @@ argparsing_args() {
                     else
                         ""
                     end
-                ' <<< "$json_args")
+                ' <<< "$json_args") || exit $?
             fi
             ;;
         *)
@@ -81,7 +104,7 @@ argparsing_args() {
             output="$output $this_output"
         fi
     done
-    logging debug "$FUNCNAME->'$output'"
+    logging trace "${FUNCNAME[0]}->$output."
     echo -n "$output"
 }
 
@@ -92,87 +115,116 @@ argparsing_args() {
 
 # delete the complete set of unknown args
 argparsing_remove_unknown() {
-    logging debug "$FUNCNAME($*)..."
     local json_args="$1"
-    local output=$(jq -rc '.unknown |= []' <<< "$json_args")
-    logging debug "$FUNCNAME->'$output'"
-    echo "$output"
+    jq -rc '.unknown |= []' <<< "$json_args"
 }
 
 # does a field exist - give a known field name (e.g. something with names:[--rpc-url] is rpc_url)
 argparsing_has() {
-    logging debug "$FUNCNAME($*)..."
-    local json_args="$1"
-    local dest="$2"
-    local value=$(jq -rc 'getpath(["known", "'"$dest"'", "value"]) != null' <<< "$json_args")
-    logging debug "$FUNCNAME->'$value'"
+    logging trace "${FUNCNAME[0]}($*)..."
+    local dest="$1"
+    local json_args="$2"
+    local value
+    value=$(jq -rc 'getpath(["known", "'"$dest"'", "value"]) != null' <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$value."
     [[ "$value" == "true" ]] && return 0
     return 1
 }
 
 argparsing_value() {
-    logging debug "$FUNCNAME($*)..."
-    local json_args="$1"
-    local dest="$2"
-    local value=$(jq -rc ".known.$dest.value // \"\"" <<< "$json_args")
-    logging debug "$FUNCNAME->'$value'"
+    logging trace "${FUNCNAME[0]}($*)..."
+    local dest="$1"
+    local json_args="$2"
+    local value
+    value=$(jq -rc ".known.$dest.value // \"\"" <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$value."
     echo "$value"
 }
 
-# argparsing_has() {
-#     logging debug "$FUNCNAME($*)..."
-#     local json_args="$1"
-#     local dest="$2"
-#     local value=$(jq -rc "getpath([\"known\", \"$dest\"]) != null" <<< "$json_args")
-#     logging debug "$FUNCNAME->'$value'"
-#     [[ "$value" == "true" ]] && return 0
-#     return 1
-# }
-
-# argparsing_value_unknown() {
-#     logging debug "$FUNCNAME($*)..."
-#     local json_args="$1"
-#     local pos="$2"
-#     local value=$(jq -rc ".unknown[$pos] // \"\"" <<< "$json_args")
-#     logging debug "$FUNCNAME->'$value'"
-#     echo "$value"
-# }
+# combine argparsing_argparse with argparsing_value
+argparsing_argparse_value() {
+    local dest="$1"
+    shift 1
+    local json_args
+    json_args=$(argparsing_argparse "$@") || exit $?
+    argparsing_value "$dest" "$json_args"
+}
 
 argparsing_add() {
-    logging debug "$FUNCNAME($*)..."
-    local json_args="$1"
-    local key="$2"
+    logging trace "${FUNCNAME[0]}($*)..."
+    local key="$1"
+    local json_args="$2"
     local value="$3"
     local origin="$4"
-    local output=$(jq -rc ".known.$key = {value: \"$value\", origin: \"$origin\"}" <<< "$json_args")
-    logging debug "$FUNCNAME->'$output'"
+    local output
+    output=$(jq -rc ".known.$key = {value: \"$value\", origin: \"$origin\"}" <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
     echo "$output"
 }
 
-# takes two JSON args and merges them prioritising the second argument
+argparsing_hide() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    local key="$1"
+    local json_args="$2"
+    local output
+    output=$(jq -rc ".known.$key.value = \"***\"" <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
+    echo "$output"
+}
+
+argparsing_remove() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    local key="$1"
+    local json_args="$2"
+    local output
+    output=$(jq -c --arg key "$key" 'del(.known[$key])' <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
+    echo "$output"
+}
+
+# keep only the known fields that are in the spec
+argparsing_keep() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    local spec_json="$1"
+    local json_args="$2"
+    local output
+    output=$(jq -c --argjson spec "$spec_json" '
+        # Build the allowed keys array:
+        ($spec.arguments // []
+        | map((.names // []) | .[] | ltrimstr("--") | gsub("-"; "_"))
+        ) as $allowed
+        # Default .known to {} if null, then filter it:
+        | .known = (.known // {}
+            | with_entries(select(.key as $k | ($allowed | index($k)) != null))
+        )
+        | .
+    ' <<< "$json_args") || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
+    echo "$output"
+}
+
+
+# takes many JSON args and merges them prioritising from the last to the first
 argparsing_merge() {
-    logging debug "$FUNCNAME($*)..."
-    local defaults="$1"
-    local overrides="$2"
-    logging debug "default='$defaults'"
-    logging debug "overrides='$overrides'"
-    # merge knowns overriding from the right
-    # unknowns take from the right, even if it's empty
-    local output=$(jq -cs '{
-        known: ((.[0].known + .[1].known) // {}),
-        unknown: (.[1].unknown // [])
-        }' <(echo "$defaults") <(echo "$overrides"))
-    logging debug "$FUNCNAME->'$output'"
+    logging trace "${FUNCNAME[0]}($*)..."
+    local output
+    output=$(jq -cs '
+        reduce .[] as $item (
+            { known: {}, unknown: [] };
+            .known += ($item.known // {}) | .unknown += ($item.unknown // []) )
+        ' < <(for json in "$@"; do echo "$json"; done)) || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
     echo "$output"
 }
 
 # takes two JSON args and returns those fields in both, order defined by the first argument
 argparsing_intersection() {
-    logging debug "$FUNCNAME($*)..."
+    logging trace "${FUNCNAME[0]}($*)..."
     local a="$1"
     local b="$2"
 
-    local output=$(jq -sc '.[0] as $a | .[1] as $b |
+    local output
+    output=$(jq -sc '.[0] as $a | .[1] as $b |
         {
             known: (
             $a.known
@@ -184,8 +236,8 @@ argparsing_intersection() {
             $a.unknown
             | map(select(. as $item | $b.unknown | index($item) != null))
             )
-        }' <(echo "$a") <(echo "$b"))
-    logging debug "$FUNCNAME->'$output'"
+        }' <(echo "$a") <(echo "$b")) || exit $?
+    logging trace "${FUNCNAME[0]}->$output."
     echo "$output"
 }
 
diff --git a/bin/modules/logging b/bin/modules/logging
--- a/bin/modules/logging
+++ b/bin/modules/logging
@@ -1,64 +1,129 @@
 #!/bin/bash
+set -e -o pipefail
 
-#if [[ -n "${GUARD_SOURCING_$(echo "$(basename "$0")" | tr -c '[:alnum:]' '_'):-}" ]]; then return; fi; GUARD_SOURCING_GUARD_SOURCING_$(echo "$(basename "$0")" | tr -c '[:alnum:]' '_')=1
 if [[ -n "${GUARD_SOURCING_LOGGING:-}" ]]; then return; fi; GUARD_SOURCING_LOGGING=1
+[[ -n "${LOADING:-}" ]] && echo "loading ${BASH_SOURCE[0]}..."
 
 # set the default logging level to warn (and above)
 LOGGING_LEVEL=${LOGGING_LEVEL:-2}
 # set the default output FD, this is changed to 8 below so logging doesn't clog things up
-_logging_file_descriptor=2
+_logging_file_descriptor=1
+declare -A _logging_hidden_text
 
 logging_config() {
     LOGGING_LEVEL=$(_logging_to_value "$1")
-    logging $1 "logging level is now $1"
+    logging info "logging level is now $LOGGING_LEVEL"
+}
+
+logging_hide() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    _logging_hidden_text["$1"]="${2:-***hidden***}"
 }
 
 logging() {
-    local level_str=$(echo "$1" | tr '[:lower:]' '[:upper:]')
-    local level=$(_logging_to_value "$1")
+    local level_str
+    level_str=$(echo "$1" | tr '[:lower:]' '[:upper:]') || exit $?
+    local level
+    level=$(_logging_to_value "$1")
     shift
     local message="$*"
+    # remove hidden text
+    for key in "${!_logging_hidden_text[@]}"; do
+        local value="${_logging_hidden_text[$key]}"
+        # Replace all occurrences of key with value in the log message
+        message="${message//$key/$value}"
+    done
     # TODO: automatic indentation via $#BASH_SOURCE
     if [[ "$level" -le "$LOGGING_LEVEL" ]]; then
-        # echo "$(date '+%Y-%m-%d %H:%M:%S,%3N') - $(printf "%-5s" "$level_str") - ${BASH_SOURCE[1]}:${BASH_LINENO[0]} ${FUNCNAME[1]}(): $message" >&$_logging_file_descriptor
-        echo "$_logging_file_descriptor $(printf "%6s" "$level_str:") ${BASH_SOURCE[1]}:${BASH_LINENO[0]} ${FUNCNAME[1]}(): $message" >&$_logging_file_descriptor
+        local indentation=5
+        local indent=$(printf "%${indentation}s  ")
+        message=${message//$'\n'/$'\n'"$indent"}
+        local format
+        format=$(printf "%-${indentation}s:" "$level_str") || exit $?
+        if [[ "$LOGGING_LEVEL" -ge "3" ]]; then
+            format+=" ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" || exit $?
+            if [[ "$LOGGING_LEVEL" -ge "4" ]]; then
+                format+=" ${FUNCNAME[1]}()"
+            fi
+            format+=":"
+        fi
+        # echo "$(date '+%Y-%m-%d %H:%M:%S,%3N') - $format
+        echo "$format $message" >&"$_logging_file_descriptor"
     fi
     if [[ "$level" -lt "0" ]]; then
         exit 1
     fi
  }
 
-_logging_to_value() {
-    local level=0
-    case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
-        debug | 3) level=3
-                ;;
-        info  | 2) level=2
-                ;;
-        warn  | 1) level=1
-                ;;
-        error | 0) level=0
-                ;;
-        fail  | -1) level=-1
-                ;;
-        *)  logging fail "unrecognised logging level: $1"
+# Define the mapping array: each element is "level:number"
+_LOGGING_LEVELS=( ":2" "debug:4" "trace:3" "info:2" "warn:1" "error:0" "fail:-1" "fatal:-1" )
 
-    esac
-    echo $level
+# Lookup: given a level name, return its number.
+_logging_to_value() {
+    local name
+    # convert name to lowercase to ensure case-insensitive matching
+    name=$(echo "$1" | tr '[:upper:]' '[:lower:]')  || exit $?
+    for pair in "${_LOGGING_LEVELS[@]}"; do
+        IFS=":" read -r key value <<< "$pair"
+        if [[ "$key" == "$name" || "$value" == "$name" ]]; then
+            echo "$value"
+            return 0
+        fi
+    done
+    echo "unknown logging level: $1." >&2
+    return 1
 }
+
+# Lookup: given a level number, return the corresponding name.
+_logging_to_name() {
+    local level="$1"
+    for pair in "${_LOGGING_LEVELS[@]}"; do
+        IFS=":" read -r key value <<< "$pair"
+        if [[ "$value" -eq "$level" ]]; then
+            echo "$key"
+            return 0
+        fi
+    done
+    echo "unknown logging level name: $1." >&2
+    return 1
+}
+
+
+# _logging_to_value() {
+#     local new_level=$(echo "$1" | tr '[:upper:]' '[:lower:]')
+#     local level=2
+#     case $new_level in
+#         "")
+#                 ;;
+#         debug | 4) level=4
+#                 ;;
+#         trace | 3) level=3
+#                 ;;
+#         info  | 2) level=2
+#                 ;;
+#         warn  | 1) level=1
+#                 ;;
+#         error | 0) level=0
+#                 ;;
+#         fail | fatal | -1) level=-1
+#                 ;;
+#         *)  logging fail "unrecognised logging level: $1"
+
+#     esac
+#     echo $level
+# }
 
 # use file descriptor 8 (3-9 are available) for logging output, fail if it is already in use
 # TODO: make this number configurable (somehow?), or search for the first free one
 # as it is just sent to stdout, without buffering
 # as we're only opening it once, there is no need to close it
-
+# shellcheck disable=SC2312 # no need to check individual commands as we have set -o pipefail
 if lsof -p $$ 2>/dev/null | awk '{print $4}' | grep -q '^8'; then
     logging fail "File descriptor 8 is in use"
 else
     _logging_file_descriptor=8
     #exec 8> >(stdbuf -o0 cat)
     exec 8>&1
-
 fi
 
 # logging info "loading 'logging' from ${BASH_SOURCE[1]}"
diff --git a/bin/modules/transacting b/bin/modules/transacting
--- a/bin/modules/transacting
+++ b/bin/modules/transacting
@@ -1,142 +1,224 @@
 #!/bin/bash
+set -e -o pipefail
 
 if [[ -n "${GUARD_SOURCING_TRANSACTING:-}" ]]; then return; fi; GUARD_SOURCING_TRANSACTING=1
+[[ -n "${LOADING:-}" ]] && echo "loading ${BASH_SOURCE[0]}..."
 
-source $(dirname "${BASH_SOURCE[0]}")/logging
-source $(dirname "${BASH_SOURCE[0]}")/argparsing
+# shellcheck disable=SC1091
+source "$(dirname "${BASH_SOURCE[0]}")/logging"
+# shellcheck disable=SC1091
+source "$(dirname "${BASH_SOURCE[0]}")/argparsing"
 
-_transacting_default_options_json=""
-_transacting_default_options_spec='{"arguments": [
-        {"names": ["--rpc-url"]},
-        {"names": ["--private-key"]},
-        {"names": ["--etherscan-api-key"]}
-    ]}'
+_transacting_spec_json=""
+_transacting_fargs=(\
+    '["--rpc-url"], "default": "local"' \
+    '["--private-key"]')
 
-_transacting_deploy_arguments_spec='{"arguments": [
-        {"names": ["--constructur-args"], "nargs":"*"},
-        {"names": ["--verify", "--no-verify"], "action": "store_boolean"},
-        {"names": ["--etherscan-api-key"]}
-    ]}'
+_transacting_deploy_spec_json=""
+_transacting_deploy_fargs=(\
+    '["file_contract"], "nargs": "?"' \
+    '["--constructor-args"], "nargs":"+"' \
+    '["--broadcast", "--no-broadcast"], "action": "store_boolean", "default": true' \
+    '["--etherscan-api-key"]' \
+    '["--verify", "--no-verify"], "action": "store_boolean"')
 
+_transacting_deploy_extra_spec_json=""
+_transacting_deploy_extra_fargs=( \
+    '["--contract-name"]' \
+    '["--purpose"]')
 
-## Options:
-##   --verify                   Verify the source (needs --etherscan-api-key)
-##   --rpc-url RPC-URL          Set the URL of the RPC node to send transactions to
-##   --private-key KEY          Private key for transaction signing
-##   --etherscan-api-key KEY    Private key for transaction signing
-    ##   -h, --help             Displays this help and exists
-    ##   -v, --version          Displays output version and exists
-    ##   $PROG -l yep -q -l nop -i -l yes
-
-transacting_default_options() {
-    logging debug "_transacting_default_options_json='$_transacting_default_options_json'"
-    # return the args processed
-    argparsing_args "$_transacting_default_options_json"
+_make_spec() {
+    local combined_output
+    combined_output=$(for arr_name in "$@"; do
+        eval 'printf "%s\n" "${'"${arr_name}"'[@]}"'
+    done) || exit $?
+    local result
+    result=$(echo "$combined_output" | jq -Rsc '
+        split("\n")
+        | map(select(length > 0))
+        | map("{\"names\":" + . + "}")
+        | map(fromjson)
+        | {arguments: .}
+    ') || exit $?
+    echo "$result"
 }
 
+_transacting_all_spec=$(_make_spec _transacting_fargs _transacting_deploy_fargs _transacting_deploy_extra_fargs)
+_transacting_spec=$(_make_spec _transacting_fargs)
+_transacting_deploy_spec=$(_make_spec _transacting_deploy_fargs)
+_transacting_deploy_extra_spec=$(_make_spec _transacting_deploy_extra_fargs)
+
+forge=$(command -v forge)
+logging info "using forge at $forge."
+
+
 transacting_config_value() {
-    logging debug "$FUNCNAME($*)..."
     local field="$1"
-    local output=$(argparsing_option "$_transacting_default_options_json" "$field")
-    logging debug "$FUNCNAME()->'$output'"
-    echo "$output"
+    argparsing_value "$field" "$_transacting_spec_json"
+    argparsing_value "$field" "$_transacting_deploy_spec_json"
+    argparsing_value "$field" "$_transacting_deploy_extra_spec_json"
 }
 
 transacting_config() {
-    logging debug "$FUNCNAME($*)..."
-    _transacting_default_options_json=$(argparsing_argparse "$_transacting_default_options_spec" "$@")
-    _transacting_default_options_json=$(argparsing_remove_unknown "$_transacting_default_options_json")
+    logging trace "${FUNCNAME[0]}($*)..."
+    local json
+    json=$(argparsing_argparse "$_transacting_all_spec" "$@")
+    json=$(argparsing_remove_unknown "$json")
+    _transacting_hide_sensitive_data_in_logs "$json"
+    logging debug "json=$json."
 
-    # if [[ -z $(argparsing_has --option rpc-url -- "$_transacting_default_options_json") ]]; then
-    #     logging info "--rpc-url not given and it is never defaulted as it is dangerous"
-    #     logging info "pass --rpc-url RPC-URL into transacting_config"
-    #     logging info "where RPC-URL can be:"
-    #     logging info "    a foundry.toml \[rpc_endpoint\] e.g. \"mainnet\""
-    #     logging info " or \"http://...\""
-    #     logging fail "no rpc-url passed into transacting_config"
-    # else
-    #     logging info "rpc-url=$rpc_url"
-    # fi
+    _transacting_spec_json=$(argparsing_keep "$_transacting_spec" "$json")
+    logging trace "_transacting_spec_json=$_transacting_spec_json."
+    _transacting_deploy_spec_json=$(argparsing_keep "$_transacting_deploy_spec" "$json")
+    logging trace "_transacting_deploy_spec_json=$_transacting_deploy_spec_json."
+    _transacting_deploy_extra_spec_json=$(argparsing_keep "$_transacting_deploy_extra_spec" "$json")
+    logging trace "_transacting_deploy_extra_spec_json=$_transacting_deploy_extra_spec_json."
 
-    _transacting_default_from_env "--private-key" "PRIVATE_KEY"
-    _transacting_default_from_env "--etherscan-api-key" "ETHERSCAN_API_KEY"
+    # read environment variables or .env file, in that order of precedence
+    _transacting_spec_json=$(_transacting_default_from_env "--private-key" "PRIVATE_KEY" "$_transacting_spec_json")
+    _transacting_deploy_spec_json=$(_transacting_default_from_env "--etherscan-api-key" "ETHERSCAN_API_KEY" "$_transacting_deploy_spec_json")
+    _transacting_hide_sensitive_data_in_logs "$_transacting_spec_json" "$_transacting_deploy_spec_json"
 
-    logging info "defaults for all transactions$(transacting_default_options)"
+    # tell the user what the defaults are
+    local defaults
+    defaults=$(argparsing_args "$_transacting_spec_json") || exit $?
+    defaults+=$(argparsing_args "$_transacting_deploy_spec_json")  || exit $?
+    defaults+=$(argparsing_args "$_transacting_deploy_extra_spec_json") || exit $?
+    logging info "transaction defaults:$defaults"
 }
 
-transacting_deploy() {
-    logging debug "deploy_contract($*)"
-    local overrides_json=argparsing_argparse "$@"
+
+_transacting_deploy_contract() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    local args_json="$1"
 
     # merge the given args with the defaults
-    local args=$(argparsing_merge "$_transacting_default_options_json" "$overrides_json")
+    args_json=$(argparsing_merge "$_transacting_spec_json" "$_transacting_deploy_spec_json" "$_transacting_deploy_extra_spec_json" "$args_json")
+    logging trace "args_json=$args_json."
 
+    # get the contract to deploy
+    local file_contract
+    file_contract=$(argparsing_value "file_contract" "$args_json")
+    logging debug "deploying $file_contract."
 
+    local contract_type="${file_contract#*:}"
+    logging debug "contract_type=$contract_type."
+    local contract_name
+    contract_name=$(argparsing_value "contract_name" "$args_json")
+    logging debug "contract_name=$contract_name."
 
-    local contract_tag=$contract_name$([[ "$contract_name" == "" ]] && echo " $contract_type" || echo " ($contract_type)")${purpose:+ $purpose}
+    local purpose
+    purpose=$(argparsing_value "purpose" "$args_json")
 
-    logging info "transacting the $contract_tag contact..."
-    local cmd "forge create --rpc-url $rpc_url \
-        --private-key $private_key \
-        --etherscan-api-key $etherscan_api_key \
-        "$source_file:$contract_type" \
-        --broadcast \
-        $constructor_args \
-        "
-    logging info "$cmd"
+    local contract_tag
+    contract_tag=${contract_name}$([[ "$contract_name" == "" ]] && echo "$contract_type" || echo " ($contract_type)")${purpose:+ $purpose}
 
-    # local response=$(forge create --rpc-url $rpc_url \
-    #     --private-key $private_key \
-    #     --etherscan-api-key $etherscan_api_key \
-    #     "$source_file:$contract_type" \
-    #     --broadcast \
-    #     $constructor_args \
-    #     )
-    # logging debug "$response"
-    # local deployer=$(echo "$response" | awk '/Deployer:/ {print $2}')
-    # local address=$(echo "$response" | awk '/Deployed to:/ {print $3}')
-    # local transaction=$(echo "$response" | awk '/Transaction hash:/ {print $3}')
+    logging info "deploying the $contract_tag contract..."
+    args_json=$(argparsing_remove "purpose" "$args_json")
+    args_json=$(argparsing_remove "contract_name" "$args_json")
+    args=$(argparsing_args "$args_json" known)
+    logging debug "args=$args."
 
-    # if [ -z "$address" ]; then
-    #     #TODO manage spaces like constructor_args above
-    #     logging fail "Failed to deploy the $contract_tag contract."
-    # fi
-    # # return the result
-    # echo $address
+    # local cmd="$forge create $args"
+    # logging info "$cmd"
 
-    # logging info "Deployed the $contract_tag contact at $address"
-    # logging info "   by $deployer tx: $transaction"
-    # log_field "$name" "$address"
+    local args_array
+    eval "args_array=($args)"
+    # eval "response=\$($cmd)" || exit $?
+    logging trace "$forge" create "${args_array[@]}"
+    local response
+    response=$("$forge" create "${args_array[@]}") || exit $?
+    logging trace "forge create->${response}."
+
+    local deployer
+    deployer=$(echo "$response" | awk '/Deployer:/ {print $2}')
+    local address
+    address=$(echo "$response" | awk '/Deployed to:/ {print $3}')
+    local transaction
+    transaction=$(echo "$response" | awk '/Transaction hash:/ {print $3}')
+
+    if [ -z "$address" ]; then
+        logging fail "Failed to deploy the $contract_tag contract."
+        return 1
+    fi
+    # return the result
+    echo "$address"
+
+    logging info "Deployed the $contract_tag contact at $address"
+    logging info "   by $deployer tx: $transaction"
 }
 
-# transacting_deploy_upgradeable() {
-#     local args="$1"
-#     local contract_name=$(echo "$args" | yq ".contract-type // \"\"")
+transacting_deploy_contract() {
+    logging trace "${FUNCNAME[0]}($*)..."
+    local args_json
+    args_json=$(argparsing_argparse "$_transacting_all_spec" "$@") || exit $?
+    _transacting_hide_sensitive_data_in_logs "$args_json"
+    logging debug "args_json=$args_json."
+    _transacting_deploy_contract "$args_json"
+}
 
-#     # verify implementation
+transacting_deploy_upgradeable_contract() {
+    logging debug "deploy_upgreadable_contract($*)"
+    local args_json
+    args_json=$(argparsing_argparse "$_transacting_deploy_spec" "$@")
+    _transacting_hide_sensitive_data_in_logs "$args_json"
+    local file_contract
+    file_contract=$(argparsing_value "file_contract" "$args_json")
+    local file="${file_contract%%:*}"
+    logging debug "file=$file."
 
-#     # deploy implementation
-#     local implementation_args=$(echo "$args" | yq '. + {"purpose": "implementation"}')
-#     logging debug "implementation_args=$implementation_args"
-#     local implementation_address=$(transacting_deploy "$implementation_args")
-#     # save deployed data
+    # validate implementation
 
-#     # deploy proxy
-#     local proxy_args=$(echo "$args" | yq ". + {\"purpose\": \"UUPS proxy\",
-#         \"source-file\": \"lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol\",
-#         \"contract-name\": \"$contract_name\",
-#         \"contract-type\": \"ERC1967Proxy\",
-#         \"constructor-args\": \"$implementation_address 0x\"}")
-#     local proxy_address=$(transacting_deploy "$proxy_args")
+    # deploy implementation
+    local implementation_args
+    implementation_args=$(argparsing_add purpose "$args_json" implementation)
+    logging debug "implementation_args=$implementation_args."
+    local implementation_address
+    implementation_address=$(_transacting_deploy_contract "$implementation_args")
+    # save deployed data, for later validation
 
-#     echo $proxy
-# }
+    # deploy proxy
+    local proxy_args
+    proxy_args=$(argparsing_argparse "$_transacting_all_spec" \
+        --purpose 'UUPS proxy' \
+        'lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy' \
+        --constructor-args "$implementation_address" '0x')
+
+    local proxy_address
+    proxy_address=$(_transacting_deploy_contract "$proxy_args")
+
+    echo "$proxy_address"
+}
+
+function get_public_from_private() {
+    local private_key="$1"
+    cast wallet address --private-key "$private_key"
+}
 
 #####################################################################################
 # private functions
 
+_transacting_hide_sensitive_data_in_logs() {
+    for args_json in "$@"; do
+        for field in "private_key" "etherscan_api_key"; do
+            local value
+            value=$(argparsing_value $field "$args_json")
+            if [ -n "$value" ]; then
+                # add a user friendly replacement, e.g. public key for a private key
+                if [[ "$value" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
+                    logging info "found private key"
+                    local public_key
+                    public_key=$(get_public_from_private "$value")
+                    [ -n "$public_key" ] && replacement="***${field} [public key:$public_key]***"
+                fi
+                logging_hide "$value" "$replacement"
+            fi
+        done
+    done
+}
+
 _transacting_lookup_env() {
-    logging debug "$FUNCNAME($*)..."
+    logging trace "${FUNCNAME[0]}($*)..."
     local env_name="$1"
     # look up the environment
     local value="${!env_name}"
@@ -146,6 +228,7 @@ _transacting_lookup_env() {
     else
         # look up the .env file if it exists
         if [[ -f .env ]]; then
+            # shellcheck disable=SC1091 # file exists check above
             source .env
             value="${!env_name}"
             logging debug "   .env $env_name=$value"
@@ -154,21 +237,25 @@ _transacting_lookup_env() {
             fi
         fi
     fi
-    logging debug "$FUNCNAME()->'$value'"
+    logging trace "${FUNCNAME[0]}->$value."
     echo "$value"
 }
 
 # update the _transacting_config global from env, if not already there
 _transacting_default_from_env() {
-    logging debug "$FUNCNAME($*)..."
+    logging trace "${FUNCNAME[0]}($*)..."
     local origin="$1" # this is the longest arg in the list (preferring long form)
     local env_name="$2" # the environment variable name
-    local field_name=$(echo "$origin" | sed -E 's/^-+//; s/-/_/g')
+    local existing_json="$3" # the existing json to update
+    local field_name
+    field_name=$(echo "$origin" | sed -E 's/^-+//; s/-/_/g') || exit $?
 
-    if ! argparsing_has "$_transacting_default_options_json" "$field_name"; then
-        local value=$(_transacting_lookup_env "$env_name")
+    if ! argparsing_has "$field_name" "$existing_json"; then
+        local value
+        value=$(_transacting_lookup_env "$env_name")
         if [ -n "$value" ]; then
-            _transacting_default_options_json=$(argparsing_add "$_transacting_default_options_json" "$field_name" "$value" "$origin")
+            existing_json=$(argparsing_add "$field_name" "$existing_json" "$value" "$origin")
         fi
     fi
+    echo "$existing_json"
 }
