argparsing_value handles arrays, returning space separated values rename defaults to defaults_* configuration happens on sourcing deploying a UUPS proxy works

diff --git a/bin/modules/transacting b/bin/modules/transacting
--- a/bin/modules/transacting
+++ b/bin/modules/transacting
@@ -9,130 +9,68 @@ source "$(dirname "${BASH_SOURCE[0]}")/logging"
 # shellcheck disable=SC1091
 source "$(dirname "${BASH_SOURCE[0]}")/argparsing"
 
-_transacting_network_args_json=""
-_transacting_network_arg_spec=('["--rpc-url"], "default": "local"')
-
-_transacting_tx_args_json=""
-_transacting_tx_arg_spec=('["--private-key"]')
-
-# todo: make no-broadcast and no-verify actually result in the argument being removed
-_transacting_deploy_args_json=""
-_transacting_deploy_arg_spec=(\
-    '["file_contract"], "nargs": "?"' \
-    '["--constructor-args"], "nargs":"+"' \
-    '["--broadcast", "--no-broadcast"], "action": "store_boolean", "default": true' \
-    '["--etherscan-api-key"]' \
-    '["--verify", "--no-verify"], "action": "store_boolean"')
-# TODO: remove these args and pass them as parameters to _deploy_contract
-_transacting_deploy_extra_args_json=""
-_transacting_deploy_extra_arg_spec=( \
-    '["--contract-name"]' \
-    '["--purpose"]')
-
-_make_spec() {
-    local combined_output
-    combined_output=$(for arr_name in "$@"; do
-        eval 'printf "%s\n" "${'"${arr_name}"'[@]}"'
-    done) || exit $?
-    local result
-    result=$(echo "$combined_output" | jq -Rsc '
-        split("\n")
-        | map(select(length > 0))
-        | map("{\"names\":" + . + "}")
-        | map(fromjson)
-        | {arguments: .}
-    ') || exit $?
-    echo "$result"
-}
-
-_transacting_all_spec=$(_make_spec _transacting_network_arg_spec _transacting_tx_arg_spec _transacting_deploy_arg_spec _transacting_deploy_extra_arg_spec)
-_transacting_network_spec=$(_make_spec _transacting_network_arg_spec)
-_transacting_tx_spec=$(_make_spec _transacting_tx_arg_spec)
-_transacting_deploy_spec=$(_make_spec _transacting_deploy_arg_spec)
-_transacting_deploy_extra_spec=$(_make_spec _transacting_deploy_extra_arg_spec)
-
-forge=$(command -v forge)
-logging info "using forge at $forge."
-
-
-transacting_config_value() {
-    local field="$1"
-    argparsing_value "$field" "$_transacting_network_args_json" \
-    || argparsing_value "$field" "$_transacting_tx_args_json" \
-    || argparsing_value "$field" "$_transacting_deploy_args_json" \
-    || argparsing_value "$field" "$_transacting_deploy_extra_args_json"
-}
-
-transacting_config() {
-    logging trace "${FUNCNAME[0]}($*)..."
+_transacting_get_contract_name() {
+    local args="$1"
     local args_json
-    args_json=$(argparsing_argparse "$_transacting_all_spec" "$@")
-    args_json=$(argparsing_remove_unknown "$args_json")
-    _transacting_hide_sensitive_data_in_logs "$args_json"
-    logging debug "args_json=$args_json."
+    local args_json=$(argsparsing_argparse '{"arguments":[
 
-    # extract the default for each level of interaction
-    _transacting_network_args_json=$(argparsing_keep "$_transacting_network_spec" "$args_json")
-    logging trace "_transacting_network_args_json=$_transacting_network_args_json."
-    _transacting_tx_args_json=$(argparsing_keep "$_transacting_tx_spec" "$args_json")
-    logging trace "_transacting_tx_args_json=$_transacting_tx_args_json."
-    _transacting_deploy_args_json=$(argparsing_keep "$_transacting_deploy_spec" "$args_json")
-    logging trace "_transacting_deploy_args_json=$_transacting_deploy_args_json."
-    _transacting_deploy_extra_args_json=$(argparsing_keep "$_transacting_deploy_extra_spec" "$args_json")
-    logging trace "_transacting_deploy_extra_args_json=$_transacting_deploy_extra_args_json."
-
-    # read environment variables or .env file, in that order of precedence
-    _transacting_tx_args_json=$(_transacting_default_from_env "--private-key" "PRIVATE_KEY" "$_transacting_tx_args_json")
-    _transacting_deploy_args_json=$(_transacting_default_from_env "--etherscan-api-key" "ETHERSCAN_API_KEY" "$_transacting_deploy_args_json")
-    _transacting_hide_sensitive_data_in_logs "$_transacting_tx_args_json" "$_transacting_deploy_args_json"
-
-    # tell the user what the defaults are
-    local defaults
-    defaults=$(argparsing_args "$_transacting_network_args_json") || exit $?
-    defaults+=$(argparsing_args "$_transacting_tx_args_json") || exit $?
-    defaults+=$(argparsing_args "$_transacting_deploy_args_json")  || exit $?
-    defaults+=$(argparsing_args "$_transacting_deploy_extra_args_json") || exit $?
-    logging info "transaction defaults:$defaults"
+        ]}' "$args")
+    argparsing_value 'contract_name' "$args_json"
 }
-
 
 _transacting_deploy_contract() {
     logging trace "${FUNCNAME[0]}($*)..."
-    local args_json="$1"
+    local purpose="$1"
+    shift
+    local args="$@"
+    logging debug "purpose=$purpose."
 
-    # merge the given args with the defaults, given args override
-    args_json=$(argparsing_merge "$_transacting_network_args_json" "$_transacting_tx_args_json" "$_transacting_deploy_args_json" "$_transacting_deploy_extra_args_json" "$args_json")
-    logging trace "args_json=$args_json."
+    # TODO: have a way to build a spec from an array of args, or have argparsing_parse_args take that array
+    local args_json=$(argparsing_argparse '{"arguments":[
+        {"names": ["--contract-name"], "nargs": "?"},
+        {"names": ["file_contract"], "nargs": 1},
+        {"names": ["--constructor-args"], "nargs":"+"},
+        {"names": ["--broadcast", "--no-broadcast"], "action": "store_boolean", "default": true},
+        {"names": ["--verify", "--no-verify"], "action": "store_boolean"}]}' $args)
+    local contract_name
+    contract_name=$(argparsing_value "contract_namer" "$args_json")
+    logging debug "contract_name=$contract_name."
 
     # get the contract to deploy
     local file_contract
     file_contract=$(argparsing_value "file_contract" "$args_json")
-    logging debug "deploying $file_contract."
-
+    logging debug "Deploying $file_contract."
     local contract_type="${file_contract#*:}"
     logging debug "contract_type=$contract_type."
-    local contract_name
-    contract_name=$(argparsing_value "contract_name" "$args_json")
     logging debug "contract_name=$contract_name."
-
-    local purpose
-    purpose=$(argparsing_value "purpose" "$args_json")
 
     local contract_tag
     contract_tag=${contract_name}$([[ "$contract_name" == "" ]] && echo "$contract_type" || echo " ($contract_type)")${purpose:+ $purpose}
 
-    logging info "deploying the $contract_tag contract..."
-    args_json=$(argparsing_remove "purpose" "$args_json")
-    args_json=$(argparsing_remove "contract_name" "$args_json")
-    args=$(argparsing_args "$args_json" known)
-    logging debug "args=$args."
+    logging info "Deploying the $contract_tag contract..."
 
-    # todo: remove the args_array?
-    local args_array
-    eval "args_array=($args)"
-    logging trace "$forge" create "${args_array[@]}"
+    # TODO: allow the defaults to be owverridden
+    local create_args="$file_contract"
+    create_args+=" --rpc-url $default_rpc_url"
+    create_args+=" --private-key $default_private_key"
+    create_args+=" --etherscan-api-key $default_etherscan_api_key"
+    local broadcast
+    broadcast=$(argparsing_value "broadcast" "$args_json")
+    [[ "$broadcast" != "false" ]] && create_args+=" --broadcast"
+    local verify
+    verify=$(argparsing_value "verify" "$args_json")
+    verify=${verify:-$default_verify}
+    # override the default value for verify (if set)
+    [[ "$verify" != "false" ]] && create_args+=" --verify"
+    # constructor args always goes last
+    local constructor_args
+    constructor_args=$(argparsing_value "constructor_args" "$args_json")
+    [ -n "$constructor_args" ] && create_args+=" --constructor-args $constructor_args"
+
+
+    logging info "$forge" create "$create_args"
     local response
-    if ! response=$("$forge" create "${args_array[@]}"); then logging fatal "forge create failed for the $contract_tag contract."; fi
+    if ! response=$("$forge" create $create_args); then logging fatal "forge create failed for the $contract_tag contract."; fi
     logging trace "forge create->${response}."
 
     local deployer
@@ -155,43 +93,26 @@ _transacting_deploy_contract() {
 }
 
 transacting_deploy_contract() {
-    logging trace "${FUNCNAME[0]}($*)..."
-    local args_json
-    args_json=$(argparsing_argparse "$_transacting_all_spec" "$@") || exit $?
-    _transacting_hide_sensitive_data_in_logs "$args_json"
-    logging debug "args_json=$args_json."
-    _transacting_deploy_contract "$args_json"
+    local args="$@"
+    _transacting_deploy_contract "non-upgradeable" "$args"
 }
 
 transacting_deploy_upgradeable_contract() {
     logging debug "deploy_upgreadable_contract($*)"
-    local args_json
-    args_json=$(argparsing_argparse "$_transacting_deploy_spec" "$@")
-    _transacting_hide_sensitive_data_in_logs "$args_json"
-    local file_contract
-    file_contract=$(argparsing_value "file_contract" "$args_json")
-    local file="${file_contract%%:*}"
-    logging debug "file=$file."
+    local args="$@"
 
     # validate implementation
 
     # deploy implementation
-    local implementation_args
-    implementation_args=$(argparsing_add purpose "$args_json" implementation)
-    logging debug "implementation_args=$implementation_args."
     local implementation_address
-    implementation_address=$(_transacting_deploy_contract "$implementation_args") || logging FATAL "failed to deploy $file_contract implementation contract."
+    implementation_address=$(_transacting_deploy_contract "implementation" "$args")
     # save deployed data, for later validation
 
     # deploy proxy
-    local proxy_args
-    proxy_args=$(argparsing_argparse "$_transacting_all_spec" \
-        --purpose 'UUPS proxy' \
+    local proxy_address
+    proxy_address=$(_transacting_deploy_contract 'UUPS proxy' \
         'lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy' \
         --constructor-args "$implementation_address" '0x')
-
-    local proxy_address
-    proxy_address=$(_transacting_deploy_contract "$proxy_args") || logging FATAL "failed to deploy $file_contract proxy contract."
 
     echo "$proxy_address"
 }
@@ -208,7 +129,7 @@ function transacting_call () {
     cast call "$@"
 }
 
-function get_public_from_private() {
+function transacting_get_public_from_private() {
     local private_key="$1"
     cast wallet address --private-key "$private_key"
 }
@@ -229,7 +150,7 @@ _transacting_hide_sensitive_data_in_logs() {
                 if [[ "$value" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
                     logging trace "found private key"
                     local public_key
-                    public_key=$(get_public_from_private "$value")
+                    public_key=$(transacting_get_public_from_private "$value")
                     [ -n "$public_key" ] && replacement="***${field} [public key:$public_key]***"
                 fi
                 logging_hide "$value" "$replacement"
@@ -296,3 +217,38 @@ _transacting_default_from_env() {
     fi
     echo "$existing_json"
 }
+
+_transacting_arg_spec='{"arguments":[
+{"names":["--rpc-url"], "default": "local"},
+{"names":["--private-key"]},
+{"names":["--etherscan-api-key"]},
+{"names": ["--verify", "--no-verify"], "action": "store_boolean"}
+]}'
+
+forge=$(command -v forge)
+logging info "using forge at $forge."
+
+args_json=$(argparsing_argparse "$_transacting_arg_spec" "$@")
+
+# read environment variables or .env file, in that order of precedence
+args_json=$(_transacting_default_from_env "--private-key" "PRIVATE_KEY" "$args_json")
+args_json=$(_transacting_default_from_env "--etherscan-api-key" "ETHERSCAN_API_KEY" "$args_json")
+_transacting_hide_sensitive_data_in_logs "$args_json"
+
+# set the global variables to be used in subsequent functions
+default_rpc_url=$(argparsing_value "rpc_url" "$args_json")
+default_private_key=$(argparsing_value "private_key" "$args_json")
+default_etherscan_api_key=$(argparsing_value "etherscan_api_key" "$args_json")
+# get the default verify - if not specified, then use the default for the rpc_url
+default_verify=$(argparsing_value "verify" "$args_json")
+if [[ "$default_verify" == "" ]]; then
+    # nothing specified, default depending on the network
+    if [[ "$default_rpc_url" == "local" ]]; then
+        default_verify="false"
+    else
+        default_verify="true"
+    fi
+fi
+
+# tell the user what the defaults are
+logging info "transaction defaults:$(argparsing_args $args_json)"
