replaced local:test with anvil added --help to deploy added a lot of error handling removed json processing from logging - it belongs with the code that is calling trace

diff --git a/bin/run/blockchain b/bin/run/blockchain
--- a/bin/run/blockchain
+++ b/bin/run/blockchain
@@ -7,12 +7,12 @@ public_from_private() {
 }
 export -f public_from_private
 
+# return the ENS name if found, otherwise return the public key
 ens_from_public() {
   local public_key="$1"
-
   local ens_name
   # shellcheck disable=SC2154
-  ens_name=$(cast lookup-ens --rpc-url $RPC_URL "$public_key" 2>/dev/null) || true
+  ens_name=$(cast lookup-ens --rpc-url $RPC_URL "$public_key" 2>/dev/null) || true # if no ENS name is found we don't fail
   [[ -n "$ens_name" ]] && echo "$ens_name" || echo "$public_key"
 }
 export -f ens_from_public
@@ -20,9 +20,9 @@ export -f ens_from_public
 chain_id() {
   local chainid_hex
   # shellcheck disable=SC2154
-  chainid_hex=$(cast chain-id --rpc-url $RPC_URL)
+  chainid_hex=$(cast chain-id --rpc-url $RPC_URL) || error "Failed to get chain ID from RPC URL: $RPC_URL"
   local result
-  result=$((16#${chainid_hex#0x}))
+  result=$((16#${chainid_hex#0x})) || error "Failed to convert chain ID from hex to decimal: $chainid_hex"
   echo "$result"
 }
 export -f chain_id
@@ -36,7 +36,7 @@ network_query() {
     debug "key=${key}."
     # shellcheck disable=SC2154
     debug "jq -r ".${key} // \"\" "$BAO_BASE_SCRIPT_DIR/bcinfo.$network.json"
-    jq -r ".${key} // \"\"" "$BAO_BASE_SCRIPT_DIR/bcinfo.$network.json"
+    jq -r ".${key} // \"\"" "$BAO_BASE_SCRIPT_DIR/bcinfo.$network.json" || error "Failed to query key '${key}' in $BAO_BASE_SCRIPT_DIR/bcinfo.$network.json"
   else
     echo ""
   fi
@@ -48,7 +48,7 @@ network_name() {
   local chain
   chain=$(chain_id) # lint-bash disable=command-substitution
   debug "looking up '${chain}' in $BAO_BASE_SCRIPT_DIR/networks.json"
-  jq -r ".[\"$chain\"] // \"\"" "$BAO_BASE_SCRIPT_DIR/networks.json"
+  jq -r ".[\"$chain\"] // \"\"" "$BAO_BASE_SCRIPT_DIR/networks.json" || error "Failed to query network name for chain ID '${chain}' in $BAO_BASE_SCRIPT_DIR/networks.json"
 }
 export -f network_name
 
diff --git a/bin/run/recording b/bin/run/recording
--- a/bin/run/recording
+++ b/bin/run/recording
@@ -62,17 +62,10 @@ has_key() {
 
 query() {
   local key="$1"
-  debug "key=${key}."
-
   _recording_config
 
-  debug "jq query: jq -r ".${key}" "${json_recording_file}""
   local result
-  result=$(jq -r ".${key}" "${json_recording_file}")
-  local status=$?
-  debug "jq \$?=${status}."
-  [[ $status -eq 0 ]] || return ${status}
-  debug "result=${result}."
+  result=$(jq -r ".${key}" "${json_recording_file}") || error "Failed to query key '${key}' in ${json_recording_file}"
   echo "${result}"
 }
 export -f query
diff --git a/bin/run/transacting b/bin/run/transacting
--- a/bin/run/transacting
+++ b/bin/run/transacting
@@ -36,26 +36,33 @@ _deploy_contract() {
   local contract_tag
   contract_tag=${key}$([[ "$key" == "" ]] && echo "$contract_type" || echo " ($contract_type)")${purpose:+ $purpose}
 
+  # check for broadcast
+  [[ -n "${BROADCAST:-}" ]] || error "we don't support dry-run deploys yet! Add --broadcast to deploy $contract_tag."
+
+  # do the deploy
   log "Deploying $contract_tag ..."
   local response
-  response=$(trace_json forge create --json --rpc-url "${RPC_URL}" --private-key "${PRIVATE_KEY}" --etherscan-api-key "${ETHERSCAN_API_KEY}" \
+  response=$(trace forge create --json --rpc-url "${RPC_URL}" --private-key "${PRIVATE_KEY}" --etherscan-api-key "${ETHERSCAN_API_KEY}" \
     "${contract_path}" ${BROADCAST:+"${BROADCAST}"} ${VERIFY:+"${VERIFY}"} \
     "${libraries[@]}" "${constructor_args[@]}") ||
     error "Failed to deploy ${contract_tag}"
-  debug "response=${response}."
+
+  # these are returned for non broadcast deploys
+  # response=$(jq 'del(.transaction.input)' <<<${response}) || error "failed to remove transaction.input from response"
+  # response=$(jq 'del(.abi)' <<<${response}) || error "failed to remove abi from response"
+
   # rename the deployedTo key to address
-  response=$(jq 'with_entries(if .key == "deployedTo" then .key = "address" else . end)' <<<"$response") ||
-    error "failed to rename deployedTo to address in response"
+  response=$(jq '.address = .deployedTo' <<<"$response") || error "failed to rename deployedTo to address in response"
   record_raw "${response}" "${key}"
 
   # record the transaction hash and block number
   local tx_hash
   tx_hash=$(query "${key}".transactionHash) || error "failed to get transaction hash from response"
-  response=$(trace_json cast tx --json $tx_hash --rpc-url $RPC_URL) ||
+  response=$(trace cast tx --json $tx_hash --rpc-url $RPC_URL) ||
     error "failed to get transaction details for ${tx_hash}"
 
   local block_number
-  block_number=$(jq -r .blockNumber <<<"${response}") || error "failed to get block number from response"
+  block_number=$(jq -r '.blockNumber' <<<"${response}") || error "failed to get block number from response"
   record $block_number "${key}".blockNumber
   log "Deployed $contract_tag."
 }
@@ -250,18 +257,14 @@ _send_transaction() {
 
   # send the transaction
   local response
-  response=$(trace_json cast send --json --rpc-url "${RPC_URL}" --private-key "${PRIVATE_KEY}" \
+  response=$(trace cast send --json --rpc-url "${RPC_URL}" --private-key "${PRIVATE_KEY}" \
     "$target_address" "${signature}" "$@") ||
     error "failed to send transaction to ${target_address} with signature ${signature} and args $*"
   echo "${response}"
 }
 
 _call() {
-  local output
-  output=$(trace cast call "--rpc-url" "${RPC_URL}" "$@") || error "failed to cast call $*"
-  # TODO: handle more data structures tuples, structs and arrays of numbers and strings
-  [[ "$output" =~ ^\".*\"$ ]] && output="${output:1:-1}" # Remove the quotes
-  echo "$output"
+  trace cast call --json "--rpc-url" "${RPC_URL}" "$@" || error "failed to cast call $*"
 }
 
 call() {
@@ -277,7 +280,12 @@ call() {
   local raw_args=()
   mapfile -t raw_args < <(query_array address "$@") || error "failed to query_array $*"
 
-  _call "${target_address}" "${sig}" "${raw_args[@]}"
+  local output
+  output=$(_call "${target_address}" "${sig}" "${raw_args[@]}") || error "failed to call ${target_key} with signature ${sig} and args ${raw_args[*]}"
+
+  # TODO: handle more data structures: tuples and values (I think structs are just tuples)
+  jq -r '.[0]' <<<"$output"
+
 }
 export -f call
 
