switch the order of parameters in record for consistency broke out resolve added appending to json arrays made grantRoles a helper function added timing

diff --git a/bin/run/recording b/bin/run/recording
--- a/bin/run/recording
+++ b/bin/run/recording
@@ -64,82 +64,97 @@ query() {
   local key="$1"
   _recording_config
 
-  local result
-  result=$(jq -r ".${key}" "${json_recording_file}") || error "Failed to query key '${key}' in ${json_recording_file}"
-  echo "${result}"
+  [[ $(has_key "${key}") == "true" ]] || error "Key '${key}' doesn't exist in ${json_recording_file}"
+  jq -r ".${key}" "${json_recording_file}" || error "Failed to query key '${key}' in ${json_recording_file}"
 }
 export -f query
+
+_resolve() {
+  local fields="$1" # Comma-separated list of fields to extract from objects
+  # arg,
+  # - if it's an object, looks for any field in the list as a sub-key and returns it if found
+  # - if it's a primitive value, returns that value
+  # - otherwise returns the argument itself
+
+  local arg="$2"
+
+  _recording_config
+
+  # Split the comma-separated fields into an array
+  local field_array=()
+  IFS=',' read -ra field_array <<<"$fields"
+
+  debug "arg=${arg}, fields=${fields}."
+
+  # default to the argument itself
+  if [[ $(has_key "${arg}") == "true" ]]; then
+    # Check if the value is an object
+    local type
+    type=$(jq -r ".${arg} | type" "${json_recording_file}") || error "Failed to determine type of '${arg}'."
+    debug "type=${type}."
+    if [[ "$type" == "object" ]]; then
+      # It's an object, try to find one of the fields
+      local found=false
+      local field
+
+      for field in "${field_array[@]}"; do
+        if [[ $(has_key "${arg}.${field}") == "true" ]]; then
+          # Check if the field is not an object
+          local field_type
+          field_type=$(jq -r ".${arg}.${field} | type" "${json_recording_file}") || error "Failed to determine type of field '${field}' in ${arg}."
+
+          if [[ "$field_type" != "object" ]]; then
+            local field_value
+            field_value=$(query "${arg}.${field}")
+            debug "${arg}.${field}->${field_value}."
+            echo "${field_value}"
+            found=true
+            break
+          fi
+        fi
+      done
+
+      # If no suitable field was found, return the argument itself
+      if [[ "$found" == "false" ]]; then
+        debug "No suitable field found in ${arg}, returning arg itself."
+        debug "${arg}->${arg}."
+        echo "${arg}"
+      fi
+    else
+      # It's not an object, just return its value
+      debug "type=${type}, returning value of ${arg}."
+      local raw_arg
+      raw_arg=$(query "${arg}")
+      debug "${arg}->${raw_arg}."
+      echo "${raw_arg}"
+    fi
+  else
+    # Key doesn't exist, return the argument itself
+    debug "!has_key, ${arg}->${arg}."
+    echo "${arg}"
+  fi
+}
+
+resolve() {
+  local arg="$1" # The argument to resolve
+  _resolve "" "${arg}" || error "Failed to resolve argument '${arg}' with fields '${fields}'."
+}
 
 # returns a line separated list of values
 # will not return objects, only primitive values
 # suitable for mapfile -t
 # returns a line separated list of values with field extraction from objects
 # first parameter is a comma-separated list of field names to extract from objects
-# for each argument:
-# - if it's an object, looks for any field in the list as a sub-key and returns it if found
-# - if it's a primitive value, returns that value
-# - otherwise returns the argument itself
-query_array() {
-  local fields="$1"
+# for each argument calls resolve, passing in the fields
+resolve_array() {
+  local fields="$1" # Comma-separated list of fields to extract from objects
   shift
-
-  # Split the comma-separated fields into an array
-  IFS=',' read -ra field_array <<<"$fields"
-
   local arg
   for arg in "$@"; do
-    debug "arg=${arg}, fields=${fields}."
-
-    # default to the argument itself
-    if [[ $(has_key "${arg}") == "true" ]]; then
-      # Check if the value is an object
-      local type
-      type=$(jq -r ".${arg} | type" "${json_recording_file}") || error "Failed to determine type of '${arg}'."
-      debug "type=${type}."
-      if [[ "$type" == "object" ]]; then
-        # It's an object, try to find one of the fields
-        local found=false
-        local field
-
-        for field in "${field_array[@]}"; do
-          if [[ $(has_key "${arg}.${field}") == "true" ]]; then
-            # Check if the field is not an object
-            local field_type
-            field_type=$(jq -r ".${arg}.${field} | type" "${json_recording_file}") || error "Failed to determine type of field '${field}' in ${arg}."
-
-            if [[ "$field_type" != "object" ]]; then
-              local field_value
-              field_value=$(query "${arg}.${field}")
-              debug "${arg}.${field}->${field_value}."
-              echo "${field_value}"
-              found=true
-              break
-            fi
-          fi
-        done
-
-        # If no suitable field was found, return the argument itself
-        if [[ "$found" == "false" ]]; then
-          debug "No suitable field found in ${arg}, returning arg itself."
-          debug "${arg}->${arg}."
-          echo "${arg}"
-        fi
-      else
-        # It's not an object, just return its value
-        debug "type=${type}, returning value of ${arg}."
-        local raw_arg
-        raw_arg=$(query "${arg}")
-        debug "${arg}->${raw_arg}."
-        echo "${raw_arg}"
-      fi
-    else
-      # Key doesn't exist, return the argument itself
-      debug "!has_key, ${arg}->${arg}."
-      echo "${arg}"
-    fi
+    _resolve "${fields}" "${arg}" || error "Failed to resolve argument '${arg}' with fields '${fields}'."
   done
 }
-export -f query_array
+export -f resolve_array
 
 # Add a field to the JSON file
 record() {
@@ -156,17 +171,18 @@ record_raw() {
 export -f record_raw
 
 # Add a nested field to an existing object
-# Usage: _record "type" "value_to_set" "key1" "key2" ... "final_key"
-# type can be "string" or "numeric"
+# Usage: _record "type" "key1" "value"
+# type can be "string" or "raw"
+# raw means any json value, including a numeric one, arrays or objects, etc.)
 _record() {
-  local value_type="$1" # Type of the value ("string" or "numeric")
+  local value_type="$1"
   debug "value_type=${value_type}."
-  local value="$2" # Value to set
-  debug "value=${value}."
-  local key="$3"
+  local key="$2"
   debug "key=${key}."
-
+  local value="$3" # Value to set
+  debug "value=${value}."
   _recording_config
+  value=$(resolve "${value}")
 
   local temp
   temp=$(mktemp)
@@ -211,4 +227,23 @@ _record() {
   [[ $status -eq 0 ]] || return ${status}
   mv "$temp" "$json_recording_file"
   cp "$json_recording_file" "$json_recording_latest_file"
+}
+
+record_append() {
+  local key="$1"
+  shift
+  _recording_config
+
+  # Read the existing array, or create an empty one if it doesn't exist
+  local existing_array
+  existing_array=$(jq -r ".${key} // []" "${json_recording_file}")
+
+  # Append the new values to the existing array
+  local new_values=("$@")
+  for value in "${new_values[@]}"; do
+    existing_array=$(echo "${existing_array}" | jq --arg v "${value}" '. + [$v]')
+  done
+
+  # Write the updated array back to the file
+  _record "raw" "${key}" "${existing_array}" || error "Failed to append values to key '${key}' in ${json_recording_file}"
 }
diff --git a/bin/run/transacting b/bin/run/transacting
--- a/bin/run/transacting
+++ b/bin/run/transacting
@@ -28,11 +28,11 @@ _deploy_contract() {
   shift 3
 
   # get the contract to deploy
-  record "${purpose}" "${key}.category" || error "failed to record ${purpose} for ${key}.category"
+  record "${key}.category" "${purpose}" || error "failed to record ${purpose} for ${key}.category"
   local contract_source=${contract_path%%:*}
-  record "${contract_source}" "${key}.contractPath" || error "failed to record ${contract_source} for ${key}.contractPath"
+  record "${key}.contractPath" "${contract_source}" || error "failed to record ${contract_source} for ${key}.contractPath"
   local contract_type="${contract_path#*:}"
-  record "${contract_type}" "${key}.contractType" || error "failed to record ${contract_type} for ${key}.contractType"
+  record "${key}.contractType" "${contract_type}" || error "failed to record ${contract_type} for ${key}.contractType"
   local contract_tag
   contract_tag=${key}$([[ "$key" == "" ]] && echo "$contract_type" || echo " ($contract_type)")${purpose:+ $purpose}
 
@@ -53,7 +53,7 @@ _deploy_contract() {
 
   # rename the deployedTo key to address
   response=$(jq '.address = .deployedTo' <<<"$response") || error "failed to rename deployedTo to address in response"
-  record_raw "${response}" "${key}"
+  record_raw "${key}" "${response}"
 
   # record the transaction hash and block number
   local tx_hash
@@ -63,7 +63,7 @@ _deploy_contract() {
 
   local block_number
   block_number=$(jq -r '.blockNumber' <<<"${response}") || error "failed to get block number from response"
-  record $block_number "${key}".blockNumber
+  record "${key}".blockNumber $block_number
   log "Deployed $contract_tag."
 }
 ###################################################################################################
@@ -97,8 +97,8 @@ deploy_contract_or_library() {
     --constructor-args)
       # handle constructor args - they are always the last argument
       local raw_args=()
-      raw_args=$(query_array address "$@") || error "failed to query_array address $*"
-      mapfile -t constructor_args <<<"$raw_args" || error "failed to query_array $*"
+      raw_args=$(resolve_array address "$@") || error "failed to resolve_array address $*"
+      mapfile -t constructor_args <<<"$raw_args" || error "failed to resolve_array $*"
       break
       ;;
     *)
@@ -179,9 +179,9 @@ upgrade_proxy() {
 
   # get the calldata for the upgradeToAndCall function
   local raw_args=()
-  raw_args=$(query_array address "$@") || error "failed to query_array address $*"
+  raw_args=$(resolve_array address "$@") || error "failed to resolve_array address $*"
   local signature_args=()
-  mapfile -t signature_args <<<"$raw_args" || error "failed to query_array $*"
+  mapfile -t signature_args <<<"$raw_args" || error "failed to resolve_array $*"
   local calldata
   calldata=$(trace cast calldata "${signature}" "${signature_args[@]}") ||
     error "failed to cast calldata for signature ${signature} with args ${raw_args[*]}"
@@ -201,8 +201,8 @@ _record_proxy_update() {
   local implementation_address
   implementation_address=$(query "${implementation_key}.address") || error "failed to query ${implementation_key} for address"
 
-  record "${implementation_key}" "${proxy_key}".implementation.contract || error "failed to record ${implementation_name} for ${proxy_key} contract"
-  record "${implementation_address}" "${proxy_key}".implementation.address || error "failed to record ${implementation_address} for ${proxy_key} contract"
+  record "${proxy_key}".implementation.contract "${implementation_key}" || error "failed to record ${implementation_name} for ${proxy_key} contract"
+  record "${proxy_key}".implementation.address "${implementation_address}" || error "failed to record ${implementation_address} for ${proxy_key} contract"
 }
 
 confirm_deployment() {
@@ -241,9 +241,9 @@ send_transaction() {
 
   # get the args
   local raw_args=()
-  raw_args=$(query_array address "$@") || error "failed to query_array address $*"
+  raw_args=$(resolve_array address "$@") || error "failed to resolve_array address $*"
   local signature_args=()
-  mapfile -t signature_args <<<"$raw_args" || error "failed to query_array $*"
+  mapfile -t signature_args <<<"$raw_args" || error "failed to resolve_array $*"
 
   # send the transaction
   _send_transaction "$target_address" "${signature}" "${signature_args[@]}" || error "failed to send transaction to ${target_key} with signature ${signature} and args ${signature_args[*]}"
@@ -278,7 +278,7 @@ call() {
 
   # get the calldata for the given function
   local raw_args=()
-  mapfile -t raw_args < <(query_array address "$@") || error "failed to query_array $*"
+  mapfile -t raw_args < <(resolve_array address "$@") || error "failed to resolve_array $*"
 
   local output
   output=$(_call "${target_address}" "${sig}" "${raw_args[@]}") || error "failed to call ${target_key} with signature ${sig} and args ${raw_args[*]}"
@@ -294,7 +294,7 @@ record_from_network() {
   local from="$2"
   local value
   value=$(network_query "${from}") || error "failed to network_query ${from}"
-  record "${value}" "${this}"
+  record "${this}" "${value}"
 }
 export -f record_from_network
 
@@ -303,6 +303,22 @@ record_from_call() {
   shift
   local value
   value=$(call "$@") || error "failed to call $*"
-  record "${value}" "${key}"
+  record "${key}" "${value}"
 }
 export -f record_from_call
+
+grantRoles() {
+  # who gets the role
+  local grantee="$1"
+  # with BaoRoles, the role is held in the implementation but accessible via the proxy or the implementation
+  local role="$2" # e.g. minter.ZERO_FEE_ROLE or Minter_v1.HARVESTER_ROLE
+
+  local granter="${role%%.*}"  # e.g. minter or Minter_v1 (proxy or implementation)
+  local role_name="${role#*.}" # e.g. ZERO_FEE_ROLE or HARVESTER_ROLE
+
+  record_from_call "${role}.value" "${granter}" "${role_name}()(uint256)"
+  send_transaction "${granter}" "grantRoles(address,uint256)" "${grantee}" "${role}.value" || error "failed to grant role ${role_name} to ${grantee} by ${granter}"
+  record_append "${role}.grantees" "${grantee}"
+
+}
+export -f grantRoles
